# Site wide configuration

title: "PortFolio Javier Melo"
description: "Proyectos de Data Scine y otras cosas de interes"
logo: ML_icon_3.png
teaser: 400x250.gif
locale: en_US
url: "https://mmistakes.github.io/jekyll-theme-skinny-bones"
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: "Michael Rose"
  web: "https://mademistakes.com"
  twitter: "mmistakes"
  bio: "Just another boring, tattooed, time traveling designer."
  avatar: "bio-photo.jpg" # 160x160 px image for author byline
  google:
    plus: "+MichaelRoseDesign"
    ad-client: "ca-pub-7328585512091257"
    ad-slot: 3049671934
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
